apiVersion: apps/v1
kind: Deployment
metadata:
  name: development-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dev-app
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
      - name: dev-container
        image: europe-west1-docker.pkg.dev/qwiklabs-gcp-01-989281f814a6/my-repository/sample-app:v2.0
        ports:
        - containerPort: 8080
